enum BC_DEFAULTS {
  GAS_PRICE = 0,
  GAS = 350000000,
  PRIVACY_FLAG = 3,
}

enum BC_ERROR_CODE {
  SC_ACCESS_ERROR = `SC-ACCESS-ERROR`,
  SC_DUPLICATE_RECORD = `SC-DUPLICATE-RECORD`,
  SC_INVALID_INPUT = `SC-INVALID-INPUT`,
  SC_INVALID_OPERATION = `SC-INVALID-OPERATION`,
  SC_RECORD_NOT_FOUND = `SC-RECORD-NOT-FOUND`,
}

enum CONTRACT_NAME {
  SS = 'storage',
}

const GET_LIST_DEFAULT_PAGE_LIMIT = {
  LIMIT: 1000,
};

enum USER_ROLE {
  FARMER = `FARMER`,
  PROCESSING_PLANT = `PROCESSING_PLANT`,
  SHIPMENT_COMPANY = `SHIPMENT_COMPANY`,
  RETAILER = `RETAILER`,
  CONSUMER = `CONSUMER`,
}

enum PROCESSING_TYPES {
  WITHERING = `WITHERING`,
  ROLLING = `ROLLING`,
  FERMENTING = `FERMENTING`,
  DRYING = `DRYING`,
  SORTING = `SORTING`,
  PACKED = `PACKED`,
}

enum STATUS_TRACK {
  TRANSIT = `TRANSIT`,
  WAREHOUSE = `WAREHOUSE`,
  RETAILER = `RETAILER`,
}

enum CARRIER {
  ROAD = 'ROAD',
  RAIL = 'RAIL',
  AIR = 'AIR',
}

//for blockchain work
enum PROCESSING_STATUS {
  'WITHERING' = 0,
  'ROLLING' = 1,
  'FERMENTING' = 2,
  'DRYING' = 3,
  'SORTING' = 4,
  'PACKED' = 5,
}

enum USER_ROLES {
  'FARMER' = 0,
  'PROCESSING_PLANT' = 1,
  'SHIPMENT_COMPANY' = 2,
  'RETAILER' = 3,
}

enum STATUS_TRACKING {
  'TRANSIT' = 0,
  'WAREHOUSE' = 1,
  'RETAILER' = 2,
}

export {
  BC_DEFAULTS,
  BC_ERROR_CODE,
  CONTRACT_NAME,
  GET_LIST_DEFAULT_PAGE_LIMIT,
  USER_ROLE,
  PROCESSING_TYPES,
  CARRIER,
  STATUS_TRACK,
  PROCESSING_STATUS,
  USER_ROLES,
  STATUS_TRACKING,
};
