enum HTTP_STATUS_CODE {
  /** HTTP_STATUS_CODE should match with ERROR_TYPE */
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,

  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  PRECONDITION_FAILED = 412,
  REQUEST_ENTITY_TOO_LARGE = 413,
  INTERNAL_SERVER_ERROR = 500,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
}

enum ERROR_TYPE {
  /** HTTP_STATUS_CODE should match with ERROR_TYPE */
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  PRECONDITION_FAILED = 'PRECONDITION_FAILED',
  REQUEST_ENTITY_TOO_LARGE = 'REQUEST_ENTITY_TOO_LARGE',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  GATEWAY_TIMEOUT = 'GATEWAY_TIMEOUT',
  COSMOS_CONNECTION_ERROR = 'COSMOS_CONNECTION_ERROR',
  COSMOS_INITIALIZATION_ERROR = 'COSMOS_INITIALIZATION_ERROR',
}

enum RESPONSE_STATUS {
  ACCEPTED = 'ACCEPTED',
  FAILED = 'FAILED',
  COMPLETED = 'COMPLETED',
  IN_PROGRESS = 'IN_PROGRESS',
}

export { HTTP_STATUS_CODE, RESPONSE_STATUS, ERROR_TYPE };
